spring:
  social:
    auto-connection-views: true
    linkedin:
      appId: XXXXXXXXXXXXXX
      appSecret: XXXXXXXXXXXXXXXX
  datasource.schema: classpath:org/springframework/social/connect/jdbc/JdbcUsersConnectionRepository.sql

application.url: http://localhost:8080